#======================= Authorization ==================
# Авторизоваться (user)
POST /fit-friends/users/login HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "email": "user@user.ru",
  "password": "123456"
}
###

# Обновить авторизацию пользователя (ожидает refresh_token, выдает повую пару токенов)
POST /fit-friends/users/refresh HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlckB1c2VyLnJ1IiwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6IlVzZXIiLCJyZWZyZXNoVG9rZW5JZCI6IjFhNTQ4MmQxLTljYzQtNDhjYy1hYjQ4LWU4MTI4OTE5ZjE3NSIsImlhdCI6MTY4MTYzODcxMSwiZXhwIjoxNjgyMjQzNTExfQ.2VEO3FlmNKmN4lCO-iS04KBHjD-SrCJz5weptImJu-I
###

#======================= User-Balance ==================
#  Получить баланс пользователя
# ?limit=50&page=0&sortType=date&sortDirection=desc
GET /fit-friends/user-balance?limit=50&page=0&sortType=date&sortDirection=desc HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlckB1c2VyLnJ1IiwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6IlVzZXIiLCJpYXQiOjE2ODIzNTQ1NTcsImV4cCI6MTY4MjM1NTQ1N30.1z1_tsXrADQO9byXLm7cDhIlrZUqsDq_8t1pVeQWaag
###

#  Обновить (только для уменьшения) баланс пользователя
PATCH  /fit-friends/user-balance HTTP/1.1
Host: localhost:3333
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlckB1c2VyLnJ1IiwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6IlVzZXIiLCJpYXQiOjE2ODIzNTQ1NTcsImV4cCI6MTY4MjM1NTQ1N30.1z1_tsXrADQO9byXLm7cDhIlrZUqsDq_8t1pVeQWaag

{
  "category": "Training",
  "serviceId": 3
}
###
