#======================= Authorization ==================
# Авторизоваться (coach)
POST /fit-friends/users/login HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "email": "user@coach.ru",
  "password": "123456"
}
###

# Обновить авторизацию пользователя (ожидает refresh_token, выдает повую пару токенов)
POST /fit-friends/users/refresh HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBjb2FjaC5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJDb2FjaCIsInJlZnJlc2hUb2tlbklkIjoiNGQ4YzY4MzItNTRhNi00NzVlLTgxY2YtNDU5MDdhOGNkODEyIiwiaWF0IjoxNjc5OTM0Mzg1LCJleHAiOjE2ODA1MzkxODV9.DCgtLqYk4BzKbVLKF4u_Bl4QiufT4xjVCw0vM-DNjXM
###

#======================= Training ==================

# Создать тренировку
POST /fit-friends/training/ HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBjb2FjaC5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY3OTg1MDQyMiwiZXhwIjoxNjc5ODUxMzIyfQ.r0ZiGkMNpz-oasU94Fc_A1kYuOChQNMJjYZQPMyNthg
Content-Type: application/json

{
  "title": "title",
  "level" : "Beginner",
  "trainingStyle" : "Yoga",
  "trainingTime" : "Max30",
  "price" : 1000,
  "caloriesLoss" : 1000,
  "description" : "description",
  "gender": "Male",
  "isSpecial" : false
}
###

# Обновить тренировку
PATCH /fit-friends/training/1 HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBjb2FjaC5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY3OTg1MDQyMiwiZXhwIjoxNjc5ODUxMzIyfQ.r0ZiGkMNpz-oasU94Fc_A1kYuOChQNMJjYZQPMyNthg
Content-Type: application/json

{
  "title": "title1",
  "level" : "Beginner",
  "trainingStyle" : "Yoga",
  "trainingTime" : "Max30",
  "price" : 2000,
  "caloriesLoss" : 3000,
  "description" : "description",
  "gender": "Male",
  "isSpecial" : true
}
###

#  Загрузка фонового изображения тренировки
POST /fit-friends/training/1/background/ HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBjb2FjaC5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY3OTkzMDkyNiwiZXhwIjoxNjc5OTMxODI2fQ.mvqbHB1BVspWuFwbudzZVUR2KTJy5wzORyjqwkWhKoU
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="background"; filename="training-4.png"
Content-Type: image/jpeg

< D:/загрузки/training-4.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

#  Получить фоновое изображение тренировки
GET /fit-friends/training/1/background/ HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBjb2FjaC5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY3OTg1NDA0OSwiZXhwIjoxNjc5ODU0OTQ5fQ.uZAmokUCWsfphof9m_yuy4jWn_u6dDXyIz3NBJ8frsc
###

#  Загрузка видео тренировки
POST /fit-friends/training/1/video/ HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBjb2FjaC5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY3OTg1MTU3OCwiZXhwIjoxNjc5ODUyNDc4fQ.EfnDjpjElRNW5ym1iDYzaMN36nLojDvocYiVeb3KAwk
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="05.jpg"
Content-Type: image/jpeg

< D:/загрузки/05.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

#  Получить видео тренировки
GET /fit-friends/training/1/video/ HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBjb2FjaC5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY3OTg1NDA0OSwiZXhwIjoxNjc5ODU0OTQ5fQ.uZAmokUCWsfphof9m_yuy4jWn_u6dDXyIz3NBJ8frsc
###

#  Получить список тренировок
# ?limit=50&page=0&sortType=date&sortDirection=desc&trainingTime=Max30
GET /fit-friends/training?limit=50&page=0&sortType=date&sortDirection=desc&priceMin=1000&priceMax=5000&ratingMin=0&ratingMax=5&trainingTime=Max30 HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBjb2FjaC5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY3OTkzNDM4NSwiZXhwIjoxNjc5OTM1Mjg1fQ.s1Qu3mhfb0wBjWeuVzIIEgphhWUJl77_1oqxJeVg4CE
###

#  Получить информацию о тренировке
GET /fit-friends/training/1 HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBjb2FjaC5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY3OTg1NDA0OSwiZXhwIjoxNjc5ODU0OTQ5fQ.uZAmokUCWsfphof9m_yuy4jWn_u6dDXyIz3NBJ8frsc
###
