#======================= Authorization ==================
# Авторизоваться (user)
POST /fit-friends/users/login HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "email": "user@user.ru",
  "password": "123456"
}
###

# Обновить авторизацию пользователя (ожидает refresh_token, выдает повую пару токенов)
POST /fit-friends/users/refresh HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlckB1c2VyLnJ1IiwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6IlVzZXIiLCJyZWZyZXNoVG9rZW5JZCI6ImVhYjk3Y2RjLWI2NzAtNDk4Ny1iNWFjLTY5ZWZmY2RhZTRlMyIsImlhdCI6MTY4MTY1OTUxNSwiZXhwIjoxNjgyMjY0MzE1fQ.rINKZCJUbjalAsKEkivHeG1jH1uzb5oGskY8pRCWJmQ
###

#======================= Notify ==================
#  Получить оповещения
# ?limit=50&page=0&sortType=date&sortDirection=desc&isChecked=false
GET /fit-friends/notify?limit=50&page=0&sortType=date&sortDirection=desc&isChecked=false HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckB1c2VyMi5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjgxNzUyOTU5LCJleHAiOjE2ODE3NTM4NTl9.1fm-_-r9yyoRKKTqHCO3avyOD4DCAkl-ypsgW1cKdMw
###

# Удалить оповещениe
DELETE /fit-friends/notify/1 HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckB1c2VyMi5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjgxNzQ4NzczLCJleHAiOjE2ODE3NDk2NzN9.tH8jqXXgqPq8g50KJgxOuOvVqF6rsnSogKFMEgDV8k8
###
