#======================= Authorization ==================
# Обновить авторизацию пользователя (ожидает refresh_token, выдает повую пару токенов)
POST /fit-friends/users/refresh HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlckB1c2VyLnJ1IiwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6IlVzZXIiLCJyZWZyZXNoVG9rZW5JZCI6IjYzODZlZGJjLTEwYzMtNDkyMi1iODA5LTQ1N2YzZjQ5NjI0NiIsImlhdCI6MTY4MjM1NDU1NywiZXhwIjoxNjgyOTU5MzU3fQ.ROdkOI7S944Co1mHpdeSGw99rpkXvZ5PaBmLHBJiNM4
###

#======================= Order ==================
# Создать заказ
POST /fit-friends/orders/ HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlckB1c2VyLnJ1IiwibmFtZSI6IkpvaG4gRG9lIiwicm9sZSI6IlVzZXIiLCJpYXQiOjE2ODIzNTQ1NTcsImV4cCI6MTY4MjM1NTQ1N30.1z1_tsXrADQO9byXLm7cDhIlrZUqsDq_8t1pVeQWaag
Content-Type: application/json

{
  "category": "Training",
  "serviceId" : 3,
  "quantity" : 2,
  "paymentMethod" : "Mir"
}
###

# Обновить заказ
PATCH /fit-friends/orders/25 HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlckB1c2VyLnJ1IiwibmFtZSI6IkZpbGlkb3IgWmVsZW5peSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjgwMTAwODgwLCJleHAiOjE2ODAxMDE3ODB9.gzSPD_HiJOXU1YAwtaYpG3NNpVwyDNmg5ybOqD6XwmM
Content-Type: application/json

{
  "quantity" : 1,
  "paymentMethod" : "Visa"
}
###

#  Получить список заказов (только для Coach)
# ?limit=50&page=0&sortType=total&sortDirection=desc
GET /fit-friends/orders?limit=50&page=1&sortType=quantity&sortDirection=asc HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBjb2FjaC5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY4MDEwNjQzMiwiZXhwIjoxNjgwMTA3MzMyfQ.tBujJ2YVoWWwjxdJWzpjJt4WVrpA9YdVTKpnS06O_4s
###

# #  Получить список покупок (User) -> UserBalance
# # ?limit=50&page=0&sortType=total&sortDirection=desc
# GET /fit-friends/orders/user?limit=50&page=1&sortType=quantity&sortDirection=asc HTTP/1.1
# Host: localhost:3333
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBjb2FjaC5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY4MDEwNjQzMiwiZXhwIjoxNjgwMTA3MzMyfQ.tBujJ2YVoWWwjxdJWzpjJt4WVrpA9YdVTKpnS06O_4s
# ###
