#======================= Authorization ==================
# Обновить авторизацию пользователя (ожидает refresh_token, выдает повую пару токенов)
POST /fit-friends/users/refresh HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlckB1c2VyLnJ1IiwibmFtZSI6IkZpbGlkb3IgWmVsZW5peSIsInJvbGUiOiJVc2VyIiwicmVmcmVzaFRva2VuSWQiOiI2MDUzNGFiYy01YzFkLTQyYmEtYTg3NC0wZTZmYjU0NzJhNjMiLCJpYXQiOjE2ODA3MTQ2OTgsImV4cCI6MTY4MTMxOTQ5OH0.XGZLYcO0wbsJUd5PDeaqP3xGvAb6yMk-wWbIF9Uf6-g
###

#======================= Order ==================
# Создать заказ
POST /fit-friends/orders/ HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlckB1c2VyLnJ1IiwibmFtZSI6IkZpbGlkb3IgWmVsZW5peSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjgwNzE0Njk4LCJleHAiOjE2ODA3MTU1OTh9.XrJnNcR6rUjByLUzmOGkkyJWHDInmq-fwAHedpcmE8c
Content-Type: application/json

{
  "category": "Training",
  "serviceId" : 3,
  "quantity" : 2,
  "paymentMethod" : "Mir"
}
###

# Обновить заказ
PATCH /fit-friends/orders/25 HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlckB1c2VyLnJ1IiwibmFtZSI6IkZpbGlkb3IgWmVsZW5peSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjgwMTAwODgwLCJleHAiOjE2ODAxMDE3ODB9.gzSPD_HiJOXU1YAwtaYpG3NNpVwyDNmg5ybOqD6XwmM
Content-Type: application/json

{
  "quantity" : 1,
  "paymentMethod" : "Visa"
}
###

#  Получить список заказов (только для Coach)
# ?limit=50&page=0&sortType=total&sortDirection=desc
GET /fit-friends/orders?limit=50&page=1&sortType=quantity&sortDirection=asc HTTP/1.1
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBjb2FjaC5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY4MDEwNjQzMiwiZXhwIjoxNjgwMTA3MzMyfQ.tBujJ2YVoWWwjxdJWzpjJt4WVrpA9YdVTKpnS06O_4s
###

# #  Получить список покупок (User) -> UserBalance
# # ?limit=50&page=0&sortType=total&sortDirection=desc
# GET /fit-friends/orders/user?limit=50&page=1&sortType=quantity&sortDirection=asc HTTP/1.1
# Host: localhost:3333
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidXNlckBjb2FjaC5ydSIsIm5hbWUiOiJKb2huIERvZSIsInJvbGUiOiJDb2FjaCIsImlhdCI6MTY4MDEwNjQzMiwiZXhwIjoxNjgwMTA3MzMyfQ.tBujJ2YVoWWwjxdJWzpjJt4WVrpA9YdVTKpnS06O_4s
# ###
