version: '3.5'
services:
  postgres:
    image: postgres:14-alpine
    container_name: fit-friends-backend
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fit-friends
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d fit-friends" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - postgres_network

  pgadmin:
    container_name: pgadmin-fit-friends
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: default@mail.local
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
